name: Build E34dash for Windows

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81'

      - name: Build with qmake
        run: |
          qmake dashmaster.pro
          mingw32-make

      - name: Find exe path
        id: find_exe
        shell: pwsh
        run: |
          $exe = Get-ChildItem -Recurse -Filter *.exe | Where-Object { $_.Name -notmatch "qmake|designer|linguist" } | Select-Object -First 1
          if (-not $exe) { Write-Error "No exe found!" }
          echo "EXE_PATH=$($exe.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "Found exe: $($exe.FullName)"

      - name: Deploy Qt dependencies
        run: |
          windeployqt "${{ env.EXE_PATH }}"

      - name: Package zip
        run: |
          $outDir = "$(Split-Path '${{ env.EXE_PATH }}')"
          $zipPath = "$env:RUNNER_TEMP\E34dash.zip"
          Compress-Archive -Path "$outDir\*" -DestinationPath $zipPath
          echo "ZIP_PATH=$zipPath" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Upload build zip
        uses: actions/upload-artifact@v4
        with:
          name: E34dash-Windows
          path: ${{ env.ZIP_PATH }}
