name: Build E34dash for Windows

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81'

      - name: Build with qmake
        run: |
          qmake dashmaster.pro
          mingw32-make

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: E34dash-exe
          path: release/*.exe
